image: python:3.10-slim

stages:
  - test

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install fastapi uvicorn opencv-python

test:
  stage: test
  script:
    - python -m py_compile main.py
    - echo "CI passed (lightweight)"